# This file is generated by matugen. Do not edit directly.

# Background and Foreground
set -U fish_color_normal '#e3e2e1'
set -U fish_color_background '#121413'

# Primary Accent Colors
set -U fish_color_command '#adcdc8'
set -U fish_color_param '#bdc9c6'
set -U fish_color_quote '#eabcb4'

# Secondary Accent Colors
set -U fish_color_redirection '#02221f'
set -U fish_color_end '#404b49'

# Error and Warning Colors
set -U fish_color_error '#ffb4ab'
set -U fish_color_warning '#93000a'

# Other common Fish colors
set -U fish_color_comment '#c1c8c6'
set -U fish_color_selection '#414847'
set -U fish_color_search_match '#414847'
set -U fish_color_operator '#8b9290'
set -U fish_color_escape '#466460'
set -U fish_color_autosuggestion '#c1c8c6'
set -U fish_color_cwd '#adcdc8'
set -U fish_color_host '#bdc9c6'
set -U fish_color_user '#eabcb4'
set -U fish_color_valid_path --underline
